### ISSUE TITLE
Default control description size

### ISSUE THREAD

**Issue by iainwp** [tdobra/tctemplate#4]
The default CD size is 6mm in Purple Pen, but TC Wizards asks you to change it to 7.  Given it's a scalable PDF could TCWizard be adjusted to work with 6mm high CDs?  One fewer thing to remember to change.

**Comment by tdobra** [comment]
I am aware that another default is to print one copy of each control description (CD) for each course. However, I cannot be sure how these will be positioned on the pages, especially since an extra line will be used if either a start control is added or the event title splits across multiple lines. Nonetheless, working with 6mm CDs and scaling up should be straightforward.

**Comment by tdobra** [comment]
Feature added to commit 108ece2.
